#!/bin/sh
if [ $(basename $PWD) != "scripts" ] ; then
	echo "Not in scripts" 1>&2
	exit 1
fi
cd ..
github_owner=mbhangui
if [ $# -gt 0 ] ; then
	distro_list=$*
else
	distro_list="archlinux almalinux8 centos7 debian11 \
		bionic focal jammy oracle8 fc36 leap15.3 leap15.4 \
		tumbleweed rockylinux8"
fi
for i in $distro_list
do
	for j in indimail-mta indimail
	do
		if [ ! -f $j/$i/Dockerfile ] ; then
			echo "$j/$i/Dockerfile: No such file or directory"
			continue
		fi
		echo -n "$i/$j: Continue (Y/N) - "
		read key
		if [ ! " $key" = " y" -a ! " $key" = " Y" ] ; then
			continue
		fi
		echo "Using $j/$i/Dockerfile for build"
		cp $j/$i/Dockerfile .
		docker build --tag "ghcr.io/$github_owner/$j:$i" .
		docker push "ghcr.io/$github_owner/$j:$i"
		docker image tag "ghcr.io/$github_owner/$j:$i" docker.io/cprogrammer/$j:$i
		docker push docker.io/cprogrammer/$j:$i
		/bin/rm -f Dockerfile
	done
done

