#!/bin/sh
if [ $(basename $PWD) != "scripts" ] ; then
	echo "Not in scripts" 1>&2
	exit 1
fi
cd ..
github_owner=mbhangui
if [ $# -gt 0 ] ; then
	distro_list=$*
else
	distro_list="almalinux8 centos7 debian11 \
		bionic focal jammy oracle8 fc36 fc37 leap15.3 leap15.4 \
		tumbleweed rockylinux8"
fi
for i in $distro_list
do
	if [ ! -f webmail/$i/Dockerfile ] ; then
		echo "webmail/$i/Dockerfile: No such file or directory"
		exit 1
	fi
	echo -n "indimail-web/$i: Continue (Y/N) - "
	read key
	if [ ! " $key" = " y" -a ! " $key" = " Y" ] ; then
		continue
	fi
	echo "Using indimail-web/$i/Dockerfile for build"
	cp webmail/$i/Dockerfile .
	if [ $? -ne 0 ] ; then
		continue
	fi
	docker build --tag "ghcr.io/$github_owner/indimail-web:$i" .
	docker image tag "ghcr.io/$github_owner/indimail-web:$i" docker.io/cprogrammer/indimail-web:$i
	/bin/rm -f Dockerfile

	echo -n "$i: Push src to ghcr.io (Y/N) - "
	read key
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		docker push "ghcr.io/$github_owner/indimail-web:$i"
	fi

	echo -n "$i: Push src to docker.io (Y/N) - "
	read key
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		docker push docker.io/cprogrammer/indimail-web:$i
	fi
done
