#!/bin/sh
if [ $(basename $PWD) != "scripts" ] ; then
	echo "Not in scripts" 1>&2
	exit 1
fi
cd ..
github_owner=mbhangui
for i in `ls indimail-src/*.bin`
do
	tag=$(basename $i | cut -d. -f1)
	pkg=$(basename $i | cut -d. -f2)
	echo -n "$i: $pkg/$tag: Continue (Y/N) - "
	read key
	if [ ! " $key" = " y" -a ! " $key" = " Y" ] ; then
		continue
	fi
	cp $i ./Dockerfile
	echo "Building cprogrammer/$pkg:$tag"
	docker build -t  cprogrammer/$pkg:$tag .
	docker image tag cprogrammer/$pkg:$tag ghcr.io/$github_owner/$pkg:$tag
	docker image tag cprogrammer/$pkg:$tag docker.io/cprogrammer/$pkg:$tag
	echo -n "$i: Push src to ghcr.io (Y/N) - "
	read key
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		docker push "ghcr.io/$github_owner/$pkg:$tag"
	fi
	echo -n "$i: Push src to docker.io (Y/N) - "
	read key
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		docker push cprogrammer/$pkg:$tag
	fi
	/bin/rm -f Dockerfile
done
