#!/bin/sh
if [ $(basename $PWD) != "scripts" ] ; then
	echo "Not in scripts" 1>&2
	exit 1
fi
github_owner=mbhangui
cd ..
for i in `ls indimail-src/*.src`
do
	echo -n "$i: Continue (Y/N) - "
	read key
	if [ ! " $key" = " y" -a ! " $key" = " Y" ] ; then
		continue
	fi
	cp $i ./Dockerfile
	tag=$(basename $i | cut -d. -f1)
	echo "Building cprogrammer/indimail-src:$tag"
	docker build -t  cprogrammer/indimail-src:$tag .
	docker image tag cprogrammer/indimail-src:$tag ghcr.io/$github_owner/indimail-src:$tag
	docker image tag cprogrammer/indimail-src:$tag docker.io/cprogrammer/indimail-src:$tag
	/bin/rm -f Dockerfile

	echo -n "$i: Push src to docker.io (Y/N) - "
	read key
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		docker push cprogrammer/indimail-src:$tag
	fi

	echo -n "$i: Push src to ghcr.io (Y/N) - "
	read key
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		docker push "ghcr.io/$github_owner/indimail-src:$tag"
	fi
done
