#!/bin/sh
if [ $(basename $PWD) != "scripts" ] ; then
	echo "Not in scripts" 1>&2
	exit 1
fi
options=$(getopt -a -n build-src -o "c:yo:" -l cmd:,yes,owner: -- "$@")
if [ $? != 0 ]; then
	(
	echo "invalid usage"
	echo "build-src [-c docker | podman] [-d distribution]"
	) 1>&2
	exit 1
fi

non_interactive=0
command=docker
github_owner=mbhangui
eval set -- "$options"
while :
do
	case "$1" in
	-c | --cmd)
	command=$2
	shift 2
	if [ " $command" != " podman" -a " $command" != " docker" ] ; then
		echo "invalid command [$command]: command should be podman or docker" 1>&2
		exit 1
	fi
	;;

	-o | --owner)
	github_owner=$2
	shift 2
	;;

	-y)
	non_interactive=1
	shift
	;;

	--) # end of options
	shift
	break
	;;

	*)
	echo "Unexpected option [$1]: this should'nt happen." 1>&2
	exit 1
	;;
	esac
done

cd ..
for i in `ls indimail-src/*.src`
do
	if [ $non_interactive -eq 0 ] ; then
		printf "%-30s Continue (Y/N) - " $i
		read key
		if [ ! " $key" = " y" -a ! " $key" = " Y" ] ; then
			continue
		fi
	fi
	cp $i ./Dockerfile
	tag=$(basename $i | cut -d. -f1)
	echo "Building cprogrammer/indimail-src:$tag"
	$command build -t  cprogrammer/indimail-src:$tag .
	$command image tag cprogrammer/indimail-src:$tag ghcr.io/$github_owner/indimail-src:$tag
	$command image tag cprogrammer/indimail-src:$tag docker.io/cprogrammer/indimail-src:$tag
	/bin/rm -f Dockerfile

	if [ $non_interactive -eq 0 ] ; then
		echo -n "$i: Push src to docker.io (Y/N) - "
		read key
	else
		key="y"
	fi
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		$command push cprogrammer/indimail-src:$tag
	fi

	if [ $non_interactive -eq 0 ] ; then
		echo -n "$i: Push src to ghcr.io (Y/N) - "
		read key
	else
		key="y"
	fi
	if [ " $key" = " y" -o " $key" = " Y" ] ; then
		$command push "ghcr.io/$github_owner/indimail-src:$tag"
	fi
done
