#!/bin/sh
my=$(whoami)
printf "%s\n%s\n" abcdefgh abcdefgh | sudo passwd $my
sudo apt-get -y update
sudo apt-get -y install curl gnupg2 apt-utils
curl -fsSL https://download.opensuse.org/repositories/home:mbhangui/xUbuntu_22.04/Release.key | \
	gpg --dearmor > home_mbhangui.gpg
sudo mv home_mbhangui.gpg /etc/apt/trusted.gpg.d/home_mbhangui.gpg
printf "deb http://download.opensuse.org/repositories/home:/mbhangui/xUbuntu_22.04/ /\n" > indimail.list
printf "Package: *\nPin: origin download.opensuse.org\nPin-Priority: 1001\n" > preferences
sudo mv indimail.list /etc/apt/sources.list.d
sudo mv preferences /etc/apt/preferences.d
sudo apt-get -y update
sudo apt-get -y install indimail-mta gsasl libnet-ssleay-perl libauthen-sasl-perl \
	libdigest-perl-md5-perl libdigest-hmac-perl
sudo /bin/rm -rf /tmp/qmail-test
