#!/bin/sh
user=mbhangui
#
testdir=/tmp/qmail-test
maildir=$testdir/$user/Maildir
homedir=$testdir/home/mail
servicedir=$testdir/service
sysconfdir=$testdir/etc/indimail
cntrldir=$sysconfdir/control
certdir=$sysconfdir/certs
logdir=$testdir/logs
bindir=/usr/bin
sbindir=/usr/sbin
qmail_newu=$sbindir/qmail-newu
qmail_start=$sbindir/qmail-start
qmail_inject=$bindir/qmail-inject
qmail_smtpd=$sbindir/qmail-smtpd
setuidgid=$bindir/setuidgid
tcpserver=$bindir/tcpserver
qmail_queue=$sbindir/qmail-queue
s_nail=/usr/bin/s-nail
smtp_port=2050
sleep_int=2
HOSTNAME=$(uname -n)

domain1=argos.indimail.org
domain2=podman.indimail.org
domain3=virtual.indimail.org
ip=192.168.2.107
password="abcdefgh12"

function check_mail()
{
	count=0
	ret=1
	(
	while true
	do
		mcount=$(sudo ls $1/new | wc -l)
		if [ $mcount -gt 0 ] ; then
			mail_file=$(sudo ls -lt $1/new|head -2|tail -1|awk '{print $9}')
			sudo /bin/rm -f $1/new/$mail_file
			return 0
		fi
		sleep 1
		count=$(expr "$count" + 1)
		echo count=$count
		if [ $count -gt 40 ] ; then
			echo "Failed to receive Mail" 1>&2
			break
		fi
	done
	return 1
	) >> $logdir/mail/mail.log 2>&1
}

function setup_maildir()
{
	if [ -d $maildir/new ] ; then
		find $maildir/new -type f -exec /bin/rm -f {} \;
	fi
	mkdir -p $cntrldir
	mkdir -p $sysconfdir/users
	echo "Creating $maildir" 1>&2
	for i in cur new tmp
	do
		mkdir -p $maildir/$i
	done
}

function shutdown_svscan()
{
	echo "Shutting down svscan"
	if [ -d $servicedir/.svscan/log ] ; then
		sudo kill $1
		sleep 5
		sudo svc -dx $servicedir/* $servicedir/*/log $servicedir/.svscan/log
	else
		sudo kill $1
		sleep 5
		sudo svc -dx $servicedir/* $servicedir/*/log
	fi
}

function setup_assign()
{
	echo "Creating $sysconfdir/users/assign" 1>&2
	(
	echo "=$user:$user:1000:1000:$testdir/$user:::"
	echo "+$user-:$user:1000:1000:$testdir/$user:-::"
	echo "."
	) > $sysconfdir/users/assign
	echo "Creating $sysconfdir/users/cdb" 1>&2
	$qmail_newu $sysconfdir/users
}

function setup_queue()
{
	echo "Creating queue in $testdir/queue" 1>&2
	sudo queue-fix $testdir/queue
}

function setup_config()
{
	echo "Creating default config files in $cntrldir" 1>&3
	env CONTROLDIR=$cntrldir config-fast $HOSTNAME 

	echo ./Maildir/                > $cntrldir/defaultdelivery
	echo TLSv1_3                   > $cntrldir/tlsclientmethod
	echo TLSv1_3                   > $cntrldir/tlsservermethod
	echo blocked@$HOSTNAME         > $cntrldir/badmailfrom
	echo blocked@$HOSTNAME         > $cntrldir/badrcptto
	echo "$domain2:127.0.0.1:2025" > $cntrldir/smtproute

	echo "Creating qmail config" 1>&3
	sudo /usr/sbin/svctool --cntrldir=$cntrldir --config=qmail
	echo "Creating openssl certificates" 1>&3
	sudo /usr/sbin/svctool --certdir=$certdir    --config=cert \
		--postmaster=postmaster@$HOSTNAME --common_name=$HOSTNAME
	sudo chown -R $user $cntrldir
	echo @$HOSTNAME > $cntrldir/nodnscheck
}

function setup_svscan_without_svscanlog()
{
	echo
	echo "Starting svscan services without svscanlog"
	sudo /bin/rm -rf $servicedir
	sudo /bin/rm -rf $logdir/smtpd
	sudo /bin/rm -rf $logdir/qmail-send

	mkdir -p $servicedir/smtpd/variables
	mkdir -p $servicedir/smtpd/log
	echo 1              > $servicedir/smtpd/variables/USE_QPWGR
	echo 0              > $servicedir/smtpd/variables/BIGTODO
	echo 23             > $servicedir/smtpd/variables/CONFSPLIT
	echo $cntrldir      > $servicedir/smtpd/variables/CONTROLDIR
	echo $testdir/queue > $servicedir/smtpd/variables/QUEUEDIR
	echo $certdir       > $servicedir/smtpd/variables/CERTDIR
	printf "#!/bin/sh\nexec envdir ./variables $tcpserver -u qmaild -g qmail -v -HR 0 $smtp_port $qmail_smtpd 2>&1\n" > $servicedir/smtpd/run
	printf "#!/bin/sh\nexec /usr/sbin/multilog t $logdir/smtpd\n" > $servicedir/smtpd/log/run
	chmod +x $servicedir/smtpd/run
	chmod +x $servicedir/smtpd/log/run

	mkdir -p $servicedir/qmail-send/variables
	mkdir -p $servicedir/qmail-send/log
	echo /bin:/usr/sbin    > $servicedir/qmail-send/variables/PATH
	echo 0                 > $servicedir/qmail-send/variables/BIGTODO
	echo 1                 > $servicedir/qmail-send/variables/QPWGR
	echo 23                > $servicedir/qmail-send/variables/CONFSPLIT
	echo $cntrldir         > $servicedir/qmail-send/variables/CONTROLDIR
	echo $testdir/queue    > $servicedir/qmail-send/variables/QUEUEDIR
	echo $sysconfdir/users > $servicedir/qmail-send/variables/ASSIGNDIR
	echo $certdir          > $servicedir/qmail-send/variables/CERTDIR
	printf "#!/bin/sh\nexec envdir ./variables $qmail_start -s ./Maildir/ 2>&1\n" > $servicedir/qmail-send/run
	printf "#!/bin/sh\nexec /usr/sbin/multilog t $logdir/qmail-send\n" > $servicedir/qmail-send/log/run
	chmod +x $servicedir/qmail-send/run
	chmod +x $servicedir/qmail-send/log/run
}

function start_svscan_without_svscanlog()
{
	(
	sudo env - \
		DISABLE_RUN=1 \
		SILENT=1 \
		PATH=/bin:/usr/sbin \
		/usr/sbin/svscan $servicedir
	) > $logdir/svscan/svscan.log 2>&1 &
	sleep 1
	svpid=$(sed -n '$p' $servicedir/.svscan.pid)
	sudo kill -0 $svpid
	if [ $? -eq 0 ] ; then
		tcount=$(expr $tcount + 1)
		echo "  testing svscan (without svscanlog) startup succeeded"
	else
		fcount=$(expr $fcount + 1)
		echo "  testing svscan (without svscanlog) startup failed"
		shutdown_svscan $svpid
		exit 1
	fi
	for i in smtpd smtpd/log qmail-send qmail-send/log
	do
		sudo svok $servicedir/smtpd
		if [ $? -eq 0 ] ; then
			tcount=$(expr $tcount + 1)
			echo "  testing service $i startup succeeded"
		else
			fcount=$(expr $fcount + 1)
			echo "  testing service $i startup failed"
			shutdown_svscan $svpid
			exit 1
		fi
	done
}

function do_setup()
{
	# basic setup for maildir, assign config and queue
	mkdir -p $homedir
	sudo /bin/rm -rf $logdir
	mkdir -p $logdir/setup
	mkdir -p $logdir/mail
	mkdir -p $logdir/qmail-send
	mkdir -p $logdir/svscan
	mkdir -p $logdir/smtpd
	mkdir -p $logdir/podman
	(
	echo "Creating maildir" 1>&3
	setup_maildir
	echo "Creating assign" 1>&3
	setup_assign
	echo "Creating config" 1>&3
	setup_config
	echo "Creating queue" 1>&3
	setup_queue
	) > $logdir/setup/setup.log 2>&1
}

function do_svscan_without_svscanlog()
{
	# start svscan without svscanlog
	echo "Setting  svscan service" 1>&3
	setup_svscan_without_svscanlog
	start_svscan_without_svscanlog
	svpid=$(sed -n '$p' $servicedir/.svscan.pid)
}

test_docker()
{
	image=$1
	what=$2
	if [ $prompt -eq 1 ] ; then
		echo -n "Test $what:$image (Y/N) - "
		read key
		if [ "$key" = "quit" ] ; then
			doquit=1
			return 0
		fi
		if [ "$key" != "Y" -a "$key" != "y" ] ; then
			return 0
		fi
	fi
	update=0
	if [ $do_update -eq 0 ] ; then
		podman image exists cprogrammer/$what:$image
		if [ $? -ne 0 ] ; then
			update=1
		fi
	else
		update=1
	fi
	if [ $update -eq 1 ] ; then
		echo "podman pull cprogrammer/$what:$image"
		podman pull cprogrammer/$what:$image
	fi
	echo "Testing $what:$image"
	id=$(podman image list -q cprogrammer/$what:$image)
	if [ $verbose -eq 1 ] ; then
		extra="--cap-add IPC_LOCK   --cap-add SYS_RESOURCE --cap-add=NET_ADMIN  --cap-add=CAP_NET_RAW --cap-add=SYS_NICE"
		echo "podman run $extra -d --rm -h $domain2 --name $what -p 2025:25 -p 2587:587 -v $homedir:/home/mail $id -d $domain2"
		podman run $extra -d --rm -h $domain2 --name $what -p 2025:25 -p 2587:587 -v $homedir:/home/mail $id -d $domain2
	else
		extra="-q --cap-add IPC_LOCK   --cap-add SYS_RESOURCE --cap-add=NET_ADMIN  --cap-add=CAP_NET_RAW --cap-add=SYS_NICE"
		podman run $extra -d --rm -h $domain2 --name $what -p 2025:25 -p 2587:587 -v $homedir:/home/mail $id -d $domain2 >/dev/null
	fi
	if [ $? -ne 0 ] ; then
		echo "Failed to run $what:$image"
		return 1
	fi
	if [ "$what" = "indimail" -o "$what" = "indimail-web" ] ; then
		case $image in
			jammy)
			for i in qmail-send.25 slowq-send inlookup.infifo indisrvr.4000
			do
				podman exec -ti $what /bin/rm -f /service/$i/variables/MYSQL_OPT_RECONNECT
				podman exec -ti $what svc -r /service/$i
			done
			;;
			#stream9)
			#podman exec -ti $what setcap -r /usr/libexec/mysqld
			#;;
		esac
		echo "Waiting 25 seconds for MySQL"
		sleep 25
	fi
	if [ $verbose -eq 1 ] ; then
		podman ps
	fi

	if [ "$what" = "indimail-mta" ] ; then
		podman exec -ti indimail-mta sh -c "printf \"&$user@$domain1\n\"         > /var/indimail/alias/.qmail-$user"
		podman exec -ti indimail-mta sh -c "printf \"$domain1:$ip:$smtp_port\n\" > /etc/indimail/control/smtproutes"
		podman exec -ti indimail-mta touch /etc/indimail/control/chkrcptdomains
		podman exec -ti indimail-mta svc -h /service/qmail-smtpd.25
		sleep $sleep_int
		swaks -S --to $user@$domain2 --from testuser01@example.com -s 127.0.0.1 -p 2025
	else
		podman exec -ti $what sh -c "printf \"$domain1:$ip:$smtp_port\n\" > /etc/indimail/control/smtproutes"
		podman exec -ti $what touch /etc/indimail/control/chkrcptdomains
		podman exec -ti $what svc -h /service/qmail-smtpd.25
		(
		echo "podman commands vadddomain, vadduser"
		podman exec -ti $what vadddomain $domain3 $password
		podman exec -ti $what vadduser $user@$domain3 $password
		echo "------------------"
		)  > $logdir/podman/$what.$image.log
		sleep $sleep_int
		swaks -S --to $user@$domain3 --from testuser01@example.com -s 127.0.0.1 -p 2025
	fi
	sleep $sleep_int
	(
	echo "------ qmail-smtpd log ------"
	podman exec -ti $what cat /var/log/svc/smtpd.25/current
	echo "------ qmail-send  log ------"
	podman exec -ti $what cat /var/log/svc/deliver.25/current
	) >> $logdir/podman/$what.$image.log
	if [ "$what" = "indimail-mta" ] ; then
		check_mail $maildir
	else
		t=$(podman exec -ti $what vuserinfo -d $user@$domain3|awk '{print $3}')
		check_mail $testdir/$t/Maildir
	fi
	if [ $? -eq 0 ] ; then
		tcount=$(expr $tcount + 1)
		echo "  testing mail send+receive via podman container succeeded"
	else
		fcount=$(expr $fcount + 1)
		echo "  testing mail send+receive via podman container failed"
		cat $logdir/podman/$what.$image.log
		echo "Press ENTER"
		read key
	fi
	echo -n "Stopping $image container="
	podman stop $what
}

usage()
{
	echo "testdocker [-y|--nprompt] [-u|--update] [-v|--verbose]" 1>&2
	exit 1
}

exec 3>&1
fcount=0
tcount=0
prompt=1
doquit=0
do_update=0
verbose=0
if [ $(basename $PWD) != "scripts" ] ; then
	echo "Not in scripts" 1>&2
	exit 1
fi
cd ..
if [ ! -x /usr/bin/podman ] ; then
	echo "podman command not found" 1>&2
	exit 1
fi
options=$(getopt -a -n testdocker -o "yuv" -l noprompt,update,verbose -- "$@")
if [ $? != 0 ]; then
  usage
fi
eval set -- "$options"
while :
do
	case "$1" in
	-y | --noprompt)
	prompt=0
	shift
	;;
	-u | --update)
	do_update=1
	shift
	;;
	-v | --verbose)
	verbose=1
	;;
	--) # end of options
	shift
	break
	;;
	*)
	echo "Unexpected option: $1 - this should'nt happen." 1>&2
	usage
	;;
	esac
done

do_setup
do_svscan_without_svscanlog
if [ $# -eq 0 ] ; then
	if [ $doquit -eq 0 ] ; then
		for i in indimail-mta/*/Dockerfile
		do
			image=$(echo $i | cut -d/ -f2)
			test_docker $image indimail-mta
			if [ $doquit -eq 1 ] ; then
				break
			fi
		done
		for i in indimail-src/*.indimail-mta.bin
		do
			image=$(echo $i | cut -d/ -f2 | cut -d. -f1)
			test_docker $image indimail-mta
			if [ $doquit -eq 1 ] ; then
				break
			fi
		done
	fi
	if [ $doquit -eq 0 ] ; then
		for i in indimail/*/Dockerfile
		do
			image=$(echo $i | cut -d/ -f2)
			test_docker $image indimail
			if [ $doquit -eq 1 ] ; then
				break
			fi
		done
		for i in indimail-src/*.indimail.bin
		do
			image=$(echo $i | cut -d/ -f2 | cut -d. -f1)
			test_docker $image indimail
			if [ $doquit -eq 1 ] ; then
				break
			fi
		done
	fi
	if [ $doquit -eq 0 ] ; then
		for i in webmail/*/Dockerfile
		do
			image=$(echo $i | cut -d/ -f2)
			test_docker $image indimail-web
			if [ $doquit -eq 1 ] ; then
				break
			fi
		done
		for i in indimail-src/*.indimail-web.bin
		do
			image=$(echo $i | cut -d/ -f2 | cut -d. -f1)
			test_docker $image indimail-web
			if [ $doquit -eq 1 ] ; then
				break
			fi
		done
	fi
else
	for i in $*
	do
		what=$(echo $i|cut -d: -f1)
		image=$(echo $i|cut -d: -f2)
		test_docker $image $what
		if [ $doquit -eq 1 ] ; then
			break
		fi
	done
fi
echo
echo "Tests Completed"
shutdown_svscan $svpid
wait
# Cleanup
sudo /bin/rm -rf $servicedir
sudo /bin/rm -rf $logdir
sudo /bin/rm -rf $testdir/queue
sudo /bin/rm -rf $sysconfdir/users
echo
if [ $fcount -eq 0 ] ; then
	echo "All $tcount tests succeeded"
else
	echo "$tcount tests succeeded, $fcount tests failed"
fi
exit 0
