name: buildall-bin push script

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          for i in almalinux8 bionic centos7 centos8 debian10 debian8 debian9 fc33 fc34 \
          focal hirsute leap15.2 leap15.3 leap42.3 oracle8 tumbleweed
          do
            for j in indimail indimail-mta
            do
              cp $j/$i/Dockerfile .
              docker build --tag "ghcr.io/${{ github.repository_owner }}/$j:$i" .
              docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
              docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/$j:$i
              docker push docker.io/cprogrammer/$j:$i
            done
          done
