# This script builds runtime images by installing packages required by indimail, indimail-mta
# from open build service. This can be used only for distributions for which obs can be used
# to build binary packages
name: buildall-bin-from-obs push script

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      distro_list:
        # Friendly description to be shown in the UI instead of 'name'
        Distro List: 'distro list'
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          set +e
          if [ -z "${{ github.event.inputs.distro_list }}"  ] ; then
            distros="almalinux8 oracle8 rockylinux8 almalinux9 oracle9 rockylinux9"
            distros="$distros debian10 debian11 bionic focal jammy fc36 fc37 leap15.4 tumbleweed"
          else
            distros="${{ github.event.inputs.distro_list }}"
          fi
          for i in $distros
          do
            for j in indimail indimail-mta
            do
              echo "Using $j/$i/Dockerfile for build"
              cp $j/$i/Dockerfile .
              docker build --tag "ghcr.io/${{ github.repository_owner }}/$j:$i" . > $i.$j.log 2>&1
              if [ $? -eq 0 ] ; then
                docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
                docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/$j:$i
                docker push docker.io/cprogrammer/$j:$i
              fi
              /bin/rm -f Dockerfile
              gzip $i.$j.log
            done
          done
      - uses: actions/upload-artifact@v2
        with:
          name: buildall-bin-from-src
          path: '*.log.gz'
