# This script builds runtime images created by build-indimail-src.yml
# the images are common for both indimail and indimail-mta
# the images have all packages required by indimail, indimail-mta installed and compiled
# using these images instead of the base images reduces build times
name: buildall-bin-from-src push script

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push source images
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          for i in alpine archlinux stream8 stream9 ubi8 gentoo
          do
            for j in indimail indimail-mta
            do
              echo "Using indimail-src/$i.$j.bin for build"
              cp indimail-src/$i.$j.bin Dockerfile
              docker build --tag "ghcr.io/${{ github.repository_owner }}/$j:$i" . > $i.$j.log
              /bin/rm -f Dockerfile
              docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
              docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/$j:$i
              docker push docker.io/cprogrammer/$j:$i
              gzip $i.$j.log
            done
          done
