# This script builds final runtime image from indimail-docker/indimail, indimail-docker/indimail-mta
# The buildtime is high because it does few things
# Download base contianer
# install devel and lib packages for indimail, indimail-mta
# (on gentoo, each and every package is built and compiled from
# source. The MySQL, cmake packages contribute to the max build time)
# build indimail, indimail-mta
name: buildall-src push script

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          for i in alpine archlinux gentoo stream8 stream9 ubi8
          do
            for j in indimail indimail-mta
            do
              echo "Using $j/$i/Dockerfile for build"
              cp $j/$i/Dockerfile .
              docker build --tag "ghcr.io/${{ github.repository_owner }}/$j:$i" .
              docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
              docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/$j:$i
              docker push docker.io/cprogrammer/$j:$i
            done
          done
