# This script builds runtime images from the source docker image
name: build-single-bin push script

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      binName:
        # Friendly description to be shown in the UI instead of 'name'
        source Name: 'bin filename without .bin extension'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: build
        run: |
          if [ -f indimail-src/"${{ github.event.inputs.binName }}".bin ] ; then
            echo "Using indimail-src/"${{ github.event.inputs.binName }}".bin for build" 
            cp indimail-src/"${{ github.event.inputs.binName }}".bin Dockerfile
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
            echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin
            docker build --tag "docker.io/cprogrammer/indimail-src:${{ github.event.inputs.binName }}" .
            docker push docker.io/cprogrammer/indimail-src:${{ github.event.inputs.binName }}
            /bin/rm -f Dockerfile
          else
            echo "indimail-src/"${{ github.event.inputs.binName }}".bin not found" 
          fi
