name: docker:almalinux8 push script

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          cp indimail/almalinux8/Dockerfile .
          for i in almalinux8 alpine archlinux bionic centos7 centos8 debian10 \
            debian8 debian9 fc33 fc34 focal gentoo hirsute leap15.2 leap15.3 \
            leap42.3 oracle8 tumbleweed ubi8 xenial
          do
            for j in indimail indimail-mta
            do
              cp $j/$i/Dockerfile .
              docker build --tag "ghcr.io/${{ github.repository_owner }}/$j:$i" .
              docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
              docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/indimail:almalinux8
              docker push docker.io/cprogrammer/$j:$i
            done
          done
