# This script builds runtime images by installing packages required by indimail, indimail-mta
# from open build service. This can be used only for distributions for which obs can be used
# to build binary packages
name: buildall-bin push script

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          for i in centos7 almalinux8 bionic debian9 debian10 debian11 focal \
          jammy oracle8 fc36 leap15.3 leap15.4 tumbleweed rockylinux8
          do
            for j in indimail indimail-mta
            do
              echo "Using $j/$i/Dockerfile for build"
              cp $j/$i/Dockerfile .
              docker build --tag "ghcr.io/${{ github.repository_owner }}/$j:$i" .
              docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
              docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/$j:$i
              docker push docker.io/cprogrammer/$j:$i
            done
          done
