# This script builds intermediate image from indimail-docker/indimail-src
# the images are common for both indimail and indimail-mta
# the images have all packages required by indimail, indimail-mta installed and compiled
# using these images instead of the base images reduces build times
# the images built here are used by build-bin-from-src.yml to build final runtime images
name: build-indimail-src push script

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push source images
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          for i in alpine archlinux ubi8 gentoo
          do
            echo "Using indimail-src/$i.src for build"
            cp indimail-src/$i.src Dockerfile
            docker build --tag "docker.io/cprogrammer/indimail-src:$i" .
            docker push docker.io/cprogrammer/indimail-src:$i
            /bin/rm -f Dockerfile
          done
