# this script builds runtime images for indimail with iwebadmin and roundcube mail
# this script uses Dockerfile which install packages required by indimail, indimail-mta from
# open build service
name: buildall-web push script

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          for i in centos7 almalinux8 bionic debian9 debian10 debian11 focal \
          jammy oracle8 fc36 leap15.3 leap15.4 tumbleweed rockylinux8
          do
            echo "Using webmail/$i/Dockerfile for build"
            cp webmail/$i/Dockerfile .
            docker build --tag "ghcr.io/${{ github.repository_owner }}/indimail-web:$i" .
            docker push "ghcr.io/${{ github.repository_owner }}/indimail-web:$i"
            docker image tag "ghcr.io/${{ github.repository_owner }}/indimail-web:$i" docker.io/cprogrammer/indimail-web:$i
            docker push docker.io/cprogrammer/indimail-web:$i
          done
