name: indimail-web:fc40 container image

on:
  push:
    paths:
      - '**/webmail/fc40/**'
      - .github/workflows/indimail-web-fc40.yml
      - '!**.md'
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          cp webmail/fc40/Dockerfile .
          docker build --tag "ghcr.io/${{ github.repository_owner }}/indimail-web:fc40" .

      - name: push
        run: |
          docker push "ghcr.io/${{ github.repository_owner }}/indimail-web:fc40"
          docker image tag "ghcr.io/${{ github.repository_owner }}/indimail-web:fc40" docker.io/cprogrammer/indimail-web:fc40
          docker push docker.io/cprogrammer/indimail-web:fc40
