name: build and push indimail-mta container image for centos8

on:
  push:
    paths:
      - '**/indimail-mta/centos8'
      - .github/workflows/indimail-mta-centos8.yml
      - '!**.md'
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login --username "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: build
        run: |
          cp indimail-mta/centos8/Dockerfile .
          docker build --tag "ghcr.io/${{ github.repository_owner }}/indimail-mta:centos8" .

      - name: push
        run: docker push "ghcr.io/${{ github.repository_owner }}/indimail-mta:centos8"
