name: indimail:mageia8 container image

on:
  push:
    paths:
      - '**/indimail/mageia8/**'
      - .github/workflows/indimail-mageia8.yml
      - '!**.md'
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io   --username "${{ github.repository_owner }}" --password-stdin
          echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io --username cprogrammer --password-stdin

      - name: build
        run: |
          cp indimail/mageia8/Dockerfile .
          docker build --tag "ghcr.io/${{ github.repository_owner }}/indimail:mageia8" .

      - name: push
        run: |
          docker push "ghcr.io/${{ github.repository_owner }}/indimail:mageia8"
          docker image tag "ghcr.io/${{ github.repository_owner }}/indimail:mageia8" docker.io/cprogrammer/indimail:mageia8
          docker push docker.io/cprogrammer/indimail:mageia8
