name: build and push indimail container image for almalinux8

on:
  push:
    paths:
      - '**/indimail/almalinux8'
      - .github/workflows/indimail-almalinux8.yml
      - '!**.md'
  workflow_dispatch:

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login --username "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: build
        run: |
          cp indimail/almalinux8/Dockerfile .
          docker build --tag "ghcr.io/${{ github.repository_owner }}/indimail:almalinux8" .

      - name: push
        run: docker push "ghcr.io/${{ github.repository_owner }}/indimail:almalinux8"
